name: birdcrumbs
favicon: null
layout_spectrum: 0
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0ffff'
    - '#c7dbec'
    - '#0f1428'
    - '#93a8a1'
    - '#485472'
  brandStrength: 0.859099492430687
  lightness: 0.4848515228368342
  saturation: 1
  rhythmicContrast: 0.9094374445267022
purpose: []
